apiVersion: v1
kind: Pod
metadata:
  name: my-pod

  labels:
    app: myapp

spec:
  containers:
    - image: mahmoudalaa1612/webimage
      name: container1
      imagePullPolicy: IfNotPresent
      ports: 
        - containerPort: 80
      
